CREATE DATABASE DINAMO;

USE DINAMO;

CREATE TABLE INVENTORY(
    UUID        VARCHAR(38) NOT NULL,
    NAME        VARCHAR(160) NOT NULL,
    DESCRIPTION TEXT,
    PRICE       FLOAT,
    AVAILABLE   BOOLEAN NOT NULL,
    IMAGE_PATH   VARCHAR(260) NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(UUID)
);

CREATE TABLE PENDING(
    UUID            VARCHAR(38) NOT NULL,
    CLIENT_NAME     VARCHAR(160) NOT NULL,
    DESCRIPTION     TEXT,
    INVENTORY_UUID  VARCHAR(38) NOT NULL,
    WORKER_UUID     VARCHAR(38) NOT NULL,
    TABLE_CODE      VARCHAR(45) NOT NULL,
    TOTAL           FLOAT,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(UUID)
);

CREATE TABLE USER(
    UUID        VARCHAR(38) NOT NULL,
    NAME        VARCHAR(160) NOT NULL,
    DELIVERIES  FLOAT,
    USERNAME    VARCHAR(160) NOT NULL,
    EMAIL       VARCHAR(200) NOT NULL,
    ROL         VARCHAR(20) NOT NULL,
    PASSWORD    VARCHAR(120) NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(UUID)
);