CREATE DATABASE DINAMO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;;

USE DINAMO;

CREATE TABLE INVENTORY(
    UUID        VARCHAR(38) NOT NULL,
    NAME        VARCHAR(160) NOT NULL,
    DESCRIPTION TEXT,
    PRICE       FLOAT,
    REF_CODE    VARCHAR(20) NOT NULL,
    AVAILABLE   BOOLEAN NOT NULL,
    IMAGE_PATH   VARCHAR(260) NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(UUID)
);

CREATE TABLE PENDING(
    UUID            VARCHAR(38) NOT NULL,
    CLIENT_NAME     VARCHAR(160) NOT NULL,
    DESCRIPTION     TEXT,
    DELIVERY        VARCHAR(38) NOT NULL,
    TABLE_CODE      VARCHAR(45) NOT NULL,
    TOTAL           FLOAT,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(UUID)
);

CREATE TABLE USER(
    UUID        VARCHAR(38) NOT NULL,
    NAME        VARCHAR(160) NOT NULL,
    DELIVERIES  FLOAT,
    USERNAME    VARCHAR(160) NOT NULL,
    EMAIL       VARCHAR(200) NOT NULL,
    ROL         VARCHAR(20) NOT NULL,
    PASSWORD    VARCHAR(120) NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(UUID)
);

INSERT INTO USER SET UUID='f2866729-0b05-466a-b947-e2c249a3fcfc', NAME='Juan Perez Solorzano', DELIVERIES=0, USERNAME='usolp', EMAIL='solorzanoperes@gmail.com', ROL='Trabajador', PASSWORD='$2a$10$4JoEs.Zyy21ObkIAjUtMm.P6wzrKcmpOwxv2rKYsF/A4FIJ7ib6Rq', CREATED_AT=NULL; /*PASSWORD->123*/